var EDGES = [
    {name: 'Ace', cost: 5, desc: '+2 to Boating, Driving, Piloting; may make soak rolls for his vehicle at –2'},
    {name: 'Acrobat', cost: 3, desc: '+2 to nimbleness-based Agility rolls; +1 Parry', affectedStat: 'parry', affectValue: 1},
    {name: 'Alertness', cost: 3, desc: '+2 to Smarts rolls made to notice events (such as burrowing attacks)'},
    {name: 'Ambidextrous', cost: 6, desc: 'Ignore –2 penalty for using off-hand'},
    {name: 'Arcane Background', cost: 10, desc: 'Allows access to supernatural powers (powers purchased separately)'},
    {name: 'Arcane Resistance', cost: 3, desc: 'Armor 2 vs. magic, +2 to resist powers'},
    {name: 'Beast Bond', cost: 3, desc: 'Character may spend bennies for animals he controls'},
    {name: 'Beast Master', cost: 0, desc: 'You gain an animal companion, paid for separately'},
    {name: 'Berserk', cost: 3, desc: 'Check the rules!'},
    {name: 'Block', cost:  3, desc: 'Parry +1', affectedStat: 'parry', affectValue: 1},
    {name: 'Brawny', cost: 3, desc: 'Toughness +1', affectedStat: 'toughness', affectValue: 1},
    {name: 'Combat Reflexes', cost: 10, desc: '+2 to recover from being Shaken'},
    {name: 'Combat Sense', cost: 3, desc: 'Opponents halve any Gang Up bonuses against him (round down). '},
    {name: 'Improved Combat Sense', cost: 6, desc: 'Opponents gain no Gang Up bonus against this warrior. '},
    {name: 'Command', cost: 5, desc: '+1 to subordinate troops within 5” to recover from being Shaken'},
    {name: 'Common Bond', cost: 3, desc: 'May spend bennies for friendly characters'},
    {name: 'Danger Sense', cost: 3, desc: 'Smarts –2 to detect surprise attacks (such as burrowing foes)'},
    {name: 'Dead Shot', cost: 3, desc: 'Double ranged damage when dealt Joker'},
    {name: 'Defender', cost: 5, desc: 'Any time a victim suffers damage within 6”, the hero may take the intended damage herself by making an Agility roll at −2 (no penalty if she was on Hold in combat). If the hero rolls a critical failure on the Agility test, she and the original target are hit by the attack (if it makes sense in the particular situation, Game Master’s call). If successful, resolve the attack against the Defender instead, who then gets one free Soak roll just as if she’d spent a Benny to do so.'},
    {name: 'Determination', cost: 5, desc: 'When the character takes enough wounds from an attack to be Incapacitated, he gets one free Soak roll.'},
    {name: 'Dodge', cost:  5, desc: '–1 to be hit with ranged attacks'},
    {name: 'Fervor', cost: 10, desc: '+1 melee damage to subordinate troops within 5”'},
    {name: 'First Strike', cost: 5, desc: 'May instantly attack one foe who moves adjacent'},
    {name: 'Fleet Footed', cost: 3, desc: '+2 Pace, d10 running die instead of d6', affectedStat: 'pace', affectValue: 2},
    {name: 'Florentine', cost: 3, desc: '+1 vs. foes with single weapon and no shield; ignore 1 point of gang up bonus'},
    {name: 'Frenzy', cost: 3, desc: '1 extra Fighting attack at –2'},
    {name: 'Giant Killer', cost: 5, desc: '+1d6 damage when attacking large creatures'},
    {name: 'Great Luck', cost: 10, desc: 'The character has two additional dedicated bennies'},
    {name: 'Hard to Kill', cost: 10, desc: 'When the character takes a wound that would put him down, roll a d6. On a 5-6, the character has 3 wounds and is Shaken instead'},
    {name: 'Harder to Kill', cost: 20, desc: 'When the character takes a wound that would put him down, roll a d6. On a 3-6, the character has 3 wounds and is Shaken instead'},
    {name: 'Healer', cost: 5, desc: '+2 to Healing rolls'},
    {name: 'Hold the Line', cost: 10, desc: 'Subordinate troops within 5” have +1 Toughness'},
    {name: 'Improved Arcane Resistance', cost: 6, desc: 'Armor 4 vs. magic, +4 to resist magic effects'},
    {name: 'Improved Block', cost: 6, desc: 'Parry +2', affectedStat: 'parry', affectValue: 2},
    {name: 'Improved Dodge', cost: 10, desc: '–2 to be hit with ranged attacks'},
    {name: 'Improved First Strike', cost: 10, desc: 'May instantly attack every foe who moves adjacent'},
    {name: 'Improved Frenzy', cost: 5, desc: '1 extra Fighting attack no penalty'},
    {name: 'Improved Level Headed', cost: 15, desc: 'Deal this unit three action cards and take the best'},
    {name: 'Improved Nerves of Steel', cost: 10, desc: 'Ignore 2 points of wound penalties'},
    {name: 'Improved Sweep', cost: 10, desc: 'Attack all adjacent foes at no penalty'},
    {name: 'Improved Tough as Nails', cost: 10, desc: 'Toughness +2', affectedStat: 'toughness', affectValue: 2},
    {name: 'Improved Trademark Weapon', cost: 6, desc: '+2 Fighting or Shooting with particular weapon'},
    {name: 'Inspire', cost: 10, desc: '+1 to Spirit rolls of subordinate troops within 5”'},
    {name: 'Iron Jaw', cost: 6, desc: 'He gets +2 to Soak rolls and Vigor rolls to avoid Knock-Out Blows.'},
    {name: 'Jack of all Trades', cost: 3, desc: 'No –2 for unskilled Smarts based attempts'},
    {name: 'Level Headed', cost: 10, desc: 'Deal this unit two action cards and take the best'},
    {name: 'Luck', cost: 5, desc: 'The character has an additional dedicated benny'},
    {name: 'Lunge', cost: 6, desc: 'The character gains +1 Reach to his weapon. He may not use this edge with Frenzy, Sweep, or any effect providing a free attack (First Strike, Counterattack, etc).'},
    {name: 'Marksman', cost: 5, desc: '+2 to Shooting rolls if the figure does not move'},
    {name: 'Master of Arms', cost: 10, desc: 'Parry +2', affectedStat: 'parry', affectValue: 2},
    {name: 'Mentalist', cost: 5, desc: '+2 to any opposed Psionics roll'},
    {name: 'Mighty Blow', cost: 5, desc: 'Double melee damage when dealt Joker'},
    {name: 'Moxie', cost: 6, desc: 'Adds +2 to all Taunt rolls and can use Taunt in place of her Smarts or Spirit when resisting a Test of Wills. '},
    {name: 'Natural Leader', cost: 5, desc: 'Leadership. Leader may give spend dedicated bennies to troops in command'},
    {name: 'Nerves of Steel', cost: 5, desc: 'Ignore 1 point of wound penalties'},
    {name: 'No Mercy', cost: 5, desc: 'May spend bennies on damage rolls'},
    {name: 'Occult', cost: 10, desc: 'Through knowledge or special gear, figures with this ability can harm Ethereal and Invulnerable creatures normally'},
    {name: 'Power Surge', cost: 5, desc: '+2d6 Power Points when dealt a Joker'},
    {name: 'Pugilist', cost:  6, desc: 'When making unarmed Fighting attacks (including natural weapons such as horns or claws), they add +1 to their Fighting rolls.'},
    {name: 'Improved Pugilist', cost:  10, desc: 'When making unarmed Fighting attacks (including natural weapons such as horns or claws), they add +2 to their Fighting rolls.'},
    {name: 'Quick', cost: 10, desc: 'The unit cannot have an action card lower than 5 (discard and re-deal until this is true)'},
    {name: 'Rock and Roll', cost: 5, desc: 'Ignore full-auto penalty if shooter doesn’t move'},
    {name: 'Rocket Jock', cost: 6, desc: 'The pilot can fire one weapon system per action without incurring a multi- action penalty while Piloting or Driving a land vehicle, or aircraft.'},
    {name: 'Royal Forester', cost: 6, desc: 'Ignores Difficult Ground when moving through the normal flora of forests and jungles (mud pits and the like still restrict movement). '},
    {name: 'Savior of the Universe', cost: 10, desc: 'The hero may forever after convert her own Bennies to Conviction tokens on a one-to-one basis. Even more importantly, she may spend Conviction on others as well as herself. '},
    {name: 'Shrug It Off', cost: 6, desc: 'At the end of a combat in which the hero suffered one or more wounds, he makes a Vigor roll (wound penalties apply). Success means he converts one wound to a level of Fatigue from Bumps and Bruises that fades in an hour. A raise converts two wounds to two levels of Fatigue. The hero cannot convert a wound if it would cause Incapacitation.'},
    {name: 'Soul Drain', cost: 5, desc: 'Check the rules!'},
    {name: 'Steady Hands', cost: 5, desc: 'Ignore unstable platform penalty'},
    {name: 'Strong Willed', cost: 3, desc: '+2 Intimidation and Taunt, and +2 to resist the same'},
    {name: 'Sweep', cost: 5, desc: 'Attack all adjacent foes at –2'},
    {name: 'Tough as Nails', cost: 5, desc: 'Toughness +1', affectedStat: 'toughness', affectValue: 1},
    {name: 'Trademark Weapon', cost: 3, desc: '+1 Fighting or Shooting with particular weapon'},
    {name: 'Two Fisted', cost: 5, desc: 'May attack with a weapon in each hand without multi-action penalty'},
    {name: 'Weapon Master', cost: 5, desc: 'Parry +1', affectedStat: 'parry', affectValue: 1},
    {name: 'Wily', cost: 6, desc: 'Whenever he gets a raise and rolls on the Creative Combat Table (page 74), he can roll twice and take the result of his choice!'},
    {name: 'Wizard', cost: 5, desc: 'Each raise reduces the cost of a cast spell by 1 point'},
    {name: 'Woodsman', cost: 3, desc: '+2 to Stealth (Stealth may be used in certain scenarios)'}
];
