var HAND_WEAPONS = [
 {name: 'Aerial Lance', damage: 'Str+d8', ap: 0, reach: 3, parry: '', twoHanded: true, cost: 13, notes: 'AP 2 when charging, Reach 3, usable only while flying. '},
 {name: 'Axe', damage: 'Str+d6', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 6},
 {name: 'Axe, Huge', damage: 'Str+d10', ap: 1, reach: 0, parry: '-1', twoHanded: true, cost: 11},
 {name: 'Axe, Ice', damage: 'Str+d6', ap: 1, reach: 0, parry: '0', twoHanded: true, cost: 8},
 {name: 'Club', damage: 'Str+d4', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 3},
 {name: 'Club, War', damage: 'Str+d8', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 10, notes: 'AP 1 vs. Rigid Armor'},
 {name: 'Dagger / Knife', damage: 'Str+d4', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 3},
 {name: 'Electro-Spear', damage: 'Str+2d10/Str+d6', ap: 10, reach: 1, parry: '+1', twoHanded: true, cost: 18},
 {name: 'Fireball Brazier', damage: 'Str+d6', ap: 0, reach: 1, parry: '', twoHanded: false, cost: 8},
 {name: 'Fork / Trident', damage: 'Str+d6', ap: 0, reach: 1, parry: '+1', twoHanded: true, cost: 11},
 {name: 'Frigian Shovel', damage: 'Str+d6', ap: 1, reach: 0, parry: '-1', twoHanded: true, cost: 5},
 {name: 'Gauntlets, Steel', damage: 'Str+d4', ap: 0, reach: 0, parry: '+1', twoHanded: true, cost: 6, notes: 'Worn by the First Lancers, the greatest fliers in the hawkmen army, these gauntlets feature a set of sharpened knuckle blades (Str+d4) and offer the user a +1 Parry bonus when worn as a pair.'},
 {name: 'Halberd', damage: 'Str+d8', ap: 0, reach: 1, parry: '', twoHanded: true, cost: 11},
 {name: 'Knife, Clasp', damage: 'Str+d4', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 3, notes: 'A large folding knife, opening takes 1 action.'},
 {name: 'Lance', damage: 'Str+d8', ap: 0, reach: 2, parry: '', twoHanded: true, cost: 10, notes: 'AP 2 when charging.'},
 {name: 'Lance, Flaming', damage: 'Str+d8+2', ap: 0, reach: 2, parry: '', twoHanded: true, cost: 16, notes: 'AP 2 when charging, roll to see if target catches fire ???'},
 {name: 'Lightning Sword', damage: 'Str+d8', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 15, notes: 'On a successful Shooting roll, can fire 2d6 lightning bolts with Range of 12/24/48'},
 {name: 'Rapier', damage: 'Str+d4', ap: 0, reach: 0, parry: '+1', twoHanded: false, cost: 6},
 {name: 'Scimitar', damage: 'Str+d8', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 9},
 {name: 'Shockstick, Silver', damage: 'Special', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 4, notes: 'Silver shocksticks are electrified weapons used for crowd control, subdual, or even torture. Uncharged shocksticks can be used as standard clubs (Str+d4), but when activated, struck targets (including Touch Attacks) must make a Vigor roll or be Stunned'},
 {name: 'Spear', damage: 'Str+d6', ap: 0, reach: 1, parry: '+1', twoHanded: true, cost: 11},
 {name: 'Spiral Blade', damage: 'Str+d8', ap: 0, reach: 0, parry: '+1', twoHanded: false, cost: 12},
 {name: 'Sword, Flame', damage: 'Str+d8+2', ap: 2, reach: 0, parry: '', twoHanded: false, cost: 19, notes: 'Roll to see if target catches fire???'},
 {name: 'Sword, Long', damage: 'Str+d8', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 9},
 {name: 'Sword, Short', damage: 'Str+d6', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 6},
 {name: 'Thunder Lance', damage: 'Str+d8', ap: 0, reach: 2, parry: '', twoHanded: true, cost: 12, notes: 'AP 2 when charging. Functions as a normal aerial lance but on first successful attack, inflicts 3d6 damage within a SBT. '},
 {name: 'Valkran Dueling Blade', damage: 'Str+d6+1', ap: 0, reach: 0, parry: '', twoHanded: false, cost: 7, notes: 'Minimum Fighting d6 to gain the +1.'},
 {name: 'Whip', damage: 'Str+d4', ap: 0, reach: 2, parry: '-1', twoHanded: false, cost: 4, notes: 'The wielder may attack as usual or use the whip to attempt a grapple at a distance equal to its Reach. When causing damage to an Entangled or Bound foe, the whip causes Str damage (not Str+d4).'},
 {name: 'Whip, Electric', damage: 'Str+d6', ap: 0, reach: 2, parry: '-1', twoHanded: false, cost: 7, notes: 'The wielder may attack as usual or use the whip to attempt a grapple at a distance equal to its Reach. When causing damage to an Entangled or Bound foe, the whip causes Str damage (not Str+d4). As Whip, but if grappling, the attacker may shock an Entangled or Bound victim as a free action (including the round the grapple is initiated). The victim must then make a Vigor roll or be Stunned'},
];
