var RANGED_WEAPONS = [
 {name: 'Acetylene Ray Gun (Heavy)', range: '150/300/600', damage: '4d10', rof: 1, ap: 15, cost: 122, special: 'Heavy Weapon, May not move unless vehicle mounted.'},
 {name: 'Acetylene Ray Gun (Light)', range: '75/150/300', damage: '2d10', rof: 1, ap: 5, cost: 60, special: 'Heavy Weapon, May not move unless vehicle mounted'},
 {name: 'Acetylene Ray Gun (Medium)', range: '100/200/400', damage: '3d10', rof: 1, ap: 15, cost: 104, special: 'Heavy Weapon, May not move unless vehicle mounted.'},
 {name: 'Acid Pistol', range: '5/10/20', damage: '2d6', rof: 1, ap: 4, cost: 37, special: 'Heavy Weapon'},
 {name: 'Acid Rifle', range: '20/40/80', damage: '2d10', rof: 1, ap: 4, cost: 47, special: 'Heavy Weapon'},
 {name: 'Atom Pistol', range: '5/10/20', damage: '2d10', rof: 1, ap: 0, cost: 33, special: 'Heavy Weapon, Cooldown, Extras Incapacitated by atom pistols are blasted to atoms. Wild Cards who are Incapacitated suffer a Permanent Injury.'},
 {name: 'Atom-Fire Pistol', range: 'Cone', damage: '2d8', rof: 1, ap: 0, cost: 13, special: 'Treat any substance hit by an Atom Fire gun as flammable.'},
 {name: 'Atom-Fire Rifle', range: 'Cone', damage: '2d12', rof: 1, ap: 0, cost: 21, special: 'Treat any substance hit by an Atom Fire gun as flammable.'},
 {name: 'Bent Ray Gun', range: '24/48/96', damage: '2d8', rof: 1, ap: 0, cost: 17, special: '“Bent rays” are particle beam weapons that can actually zigzag around objects and track a target’s heat-signature. As long as the attacker can see any part of a target, he can shoot it and ignores all cover modifiers!'},
 {name: 'Boomerang, S-shaped', range: '10/20/40', damage: 'Str+6', rof: 1, ap: 0, cost: 6, special: 'Min Agl d8, The favored weapon of the dwarfs of the Magnetic Mountains, these aerodynamic, s-shaped blades, if correctly thrown, fly in an elliptical path and return to the wielder’s hand unless they strike down their prey first. Catching a returning boomerang requires an Agility roll. Should the would-be catcher roll a critical failure, he’s struck for full damage!'},
 {name: 'Bow', range: '12/24/48', damage: '2d6', rof: 1, ap: 0, cost: 6, special: 'Min Str d6'},
 {name: 'Bow, Arborian', range: '20/40/80', damage: '2d6', rof: 1, ap: 0, cost: 7, special: 'Min Str d6. '},
 {name: 'Cannon (Large)', range: '75/150/300', damage: '6d8', rof: 1, ap: 16, cost: 136, special: 'Heavy Weapon. Large Burst Template.'},
 {name: 'Cannon (Medium)', range: '75/150/300', damage: '5d8', rof: 1, ap: 10, cost: 110, special: 'Heavy Weapon. Large Burst Template.'},
 {name: 'Cannon (Small)', range: '50/100/200', damage: '4d8', rof: 1, ap: 8, cost: 91, special: 'Heavy Weapon. Large Burst Template.'},
 {name: 'Cold Cannon (Small)', range: 'Cone', damage: 'Special', rof: 1, ap: 0, cost: 9, special: 'A target hit by a cold cannon beam must make a Vigor roll (at –2 with a raise on the attack). With a raise, the target is unaffected. A success means he’s Entangled, and failure means he’s frozen solid and Bound. Due to the nature of the ice, victims may only use Strength to break free, not Agility. A frozen victim thaws in 1d6 Turns under normal conditions, but a companion can spend his entire turn helping the and the formerly frozen ally is then Entangled.'},
 {name: 'Dagger / Knife, throwing', range: '3/6/12', damage: 'Str+d4', rof: 1, ap: 0, cost: 1},
 {name: 'Electro-Rifle', range: '24/48/96', damage: '2d10', rof: 1, ap: 0, cost: 13, special: 'Cooldown. After a target is hit, he must make a Vigor roll or be Stunned (at –2 with a raise on the attack roll). A character stunned by an electric weapon falls prone and can’t take any actions or move. Attacks against him get the Drop. At the start of each of his turns thereafter, he automatically makes a Vigor roll as a free action to revive. Success means he revives but is Shaken, a raise means he revives and is not Shaken.'},
 {name: 'Electro-Shock Gun', range: '12/24/48', damage: 'None', rof: 1, ap: 0, cost: 9, special: 'After a target is hit, he must make a Vigor roll or be Stunned (at –2 with a raise on the attack roll). A character stunned by an electric weapon falls prone and can’t take any actions or move. Attacks against him get the Drop. At the start of each of his turns thereafter, he automatically makes a Vigor roll as a free action to revive. Success means he revives but is Shaken, a raise means he revives and is not Shaken.'},
 {name: 'Electro-Spear', range: '3/6/12', damage: '2d10', rof: 1, ap: 10, cost: 7, special: 'This is a single-use weapon, though it is only discharged on a successful hit. Spear may be used in melee or thrown. Reach 1. After discharge it may be wielded as a normal spear. Users with a Shooting skill of d8 or higher inflict an additional 1d6 damage. Min Str d6.'},
 {name: 'Energy Trident', range: '5/10/20', damage: '2d10', rof: 1, ap: 0, cost: 2, special: 'Users with a Shooting skill of d8 or higher inflict an additional 1d6 damage. Min Str d6.'},
 {name: 'Explosol', range: '4/8/16', damage: '2d10', rof: 1, ap: 0, cost: 4, special: 'One-Shot, Large Blast Template.'},
 {name: 'Fireball Brazier', range: '3/6/12', damage: '2d6', rof: 2, ap: 0, cost: 15, special: 'Minimum Agility d8. Used by Savage Men and dual-wielded. These fire buckets can toss small flaming rocks. When thrown, they cause 2d6 damage. Targets may catch fire. Affects least Armored area. If used in melee they have Reach 1, and do Str+d6 damage. '},
 {name: 'Flame-Gun Rifle', range: 'Cone', damage: '2d8', rof: 1, ap: 0, cost: 20, special: 'Min Str d6. May set targets on fire. Affects target’s least armored area.'},
 {name: 'Flamol Thrower (Vehicular)', range: 'Cone', damage: '3d10', rof: 1, ap: 0, cost: 49, special: 'Heavy Weapon. May not move unless vehicle mounted. May start fires. May be fired as Cone, or Medium Burst Template up to 18” distant. Affects target’s least armored area.'},
 {name: 'Flamol Thrower', range: 'Cone', damage: '2d10', rof: 1, ap: 0, cost: 34, special: 'Heavy Weapon, Min Str d8, May start fires. May be fired as Cone, or Medium Burst Template up to 18” distant. Affects target’s least armored area.'},
 {name: 'Gas Pistol', range: 'Cone', damage: 'None', rof: 1, ap: 0, cost: 9, special: 'Vigor roll –2 or be knocked Prone and Incapacitated for 2d4 rounds.'},
 {name: 'Heat Gun', range: '12/24/48', damage: '2d10', rof: 1, ap: 4, cost: 46, special: 'Heavy Weapon'},
 {name: 'Heavy Radium Cannon', range: '24/48/96', damage: '4d8', rof: 1, ap: 2, cost: 59, special: 'Min Str d8, Heavy Weapon, Medium Blast Template, Snapfire.'},
 {name: 'Ice Gun', range: '5/10/20', damage: 'None', rof: 1, ap: 0, cost: 8, special: 'Anyone struck by an ice gun’s beam must make a Vigor roll (at –2 with a raise on the attack). With a raise, the target is unaffected. A success means he’s Entangled, and failure means he’s frozen solid and Bound. Due to the nature of the ice, victims may only use Strength to break free, not Agility. A frozen victim thaws in 1d6 Turns under normal conditions, but a companion can spend his entire turn helping the and the formerly frozen ally is then Entangled.'},
 {name: 'Light Pistol', range: '12/24/48', damage: '2d6', rof: 1, ap: 0, cost: 6, special: 'May be overcharged, add another die to its damage (3d6 for pistols and 3d8 for rifles). It then requires Cooldown'},
 {name: 'Light Rifle', range: '24/48/96', damage: '2d8', rof: 1, ap: 0, cost: 12, special: 'May be overcharged, add another die to its damage (3d6 for pistols and 3d8 for rifles). It then requires Cooldown'},
 {name: 'Mini-Crossbow', range: '6/12/24', damage: '2d4', rof: 1, ap: 1, cost: 4},
 {name: 'Net Gun', range: '5/10/20', damage: 'Special', rof: 1, ap: 0, cost: 3, special: 'With a successful hit, targets are Entangled, with a raise, they’re Bound.'},
 {name: 'Pistol (.38)', range: '12/24/48', damage: '2d6-1', rof: 1, ap: 0, cost: 5},
 {name: 'Power Pistol', range: '20/40/80', damage: '2d6', rof: 1, ap: 0, cost: 15, special: 'Overpower to add 2d6 fire damage or AP 2 (only one effect allowed per shot). '},
 {name: 'Precision Atom Rifle', range: '50/100/200', damage: '2d10+1', rof: 4, ap: 4, cost: 58, special: 'Min Str d6. Snapfire.'},
 {name: 'Ray Gun Pistol', range: '12/24/48', damage: '2d6+2', rof: 1, ap: 0, cost: 8, special: 'Semi-Auto'},
 {name: 'Ray Gun Rifle', range: '24/48/96', damage: '2d8', rof: 1, ap: 0, cost: 12, special: 'Semi-Auto'},
 {name: 'Red Monkey Sling', range: '4/8/16', damage: 'Str+d4', rof: 1, ap: 0, cost: 1},
 {name: 'Rifle (.30)', range: '24/48/96', damage: '2d8', rof: 1, ap: 2, cost: 18, special: 'Semi-Auto. Min Str d6.'},
 {name: 'Rocket (Heavy)', range: '200/400/800', damage: '6d8', rof: 1, ap: 15, cost: 142, special: 'Heavy Weapon. Medium Blast Template.'},
 {name: 'Rocket (Light)', range: '200/400/800', damage: '6d6', rof: 1, ap: 8, cost: 110, special: 'Heavy Weapon. Small Blast Template.'},
 {name: 'Rocket, Anti-Tank', range: '200/400/800', damage: '6d6', rof: 1, ap: 20, cost: 146, special: 'Heavy Weapon. Small Blast Template.'},
 {name: 'Savage Blowgun', range: '3/6/9', damage: '2d4', rof: 1, ap: 0, cost: 6, special: 'Each barb is wrapped with dalos fibers that require a Vigor roll or target is Fatigued'},
 {name: 'Shotgun (12g)', range: '12/24/48', damage: '1-3d6', rof: 1, ap: 0, cost: 12, special: '???'},
 {name: 'Signal Gun Pistol', range: '10/20/40', damage: '2d6', rof: 2, ap: 0, cost: 16, special: 'Semi-Auto'},
 {name: 'Sky Pistol', range: '15/30/60', damage: '2d6', rof: 1, ap: 2, cost: 18, special: 'Semi-Auto, Stun Setting'},
 {name: 'Sky Rifle (Hawkmen)', range: '50/100/200', damage: '2d10', rof: 1, ap: 2, cost: 19, special: 'Min Str d6, Snapfire, –2 penalty when not flying.'},
 {name: 'Sky Rifle', range: '30/60/120', damage: '3d6', rof: 3, ap: 2, cost: 46, special: '3RB, Semi-Auto, no recoil penalty, Stun setting. '},
 {name: 'Sleep Gas Globe', range: '5/10/20', damage: 'Special', rof: 1, ap: 0, cost: 13, special: 'The spheres shatter upon impact and fill an area with gas in a Medium Burst Template. Anyone caught in the area of effect (or in it on subsequent rounds) must make a Vigor roll at –2. If failed, the character falls into a deep sleep for 2d6 hours. The gas disperses safely after three rounds.'},
 {name: 'Sleep-Gas Gun', range: 'Cone', damage: 'Special', rof: 1, ap: 0, cost: 14, special: 'Fully charged with 6 vials of asphyxoil.'},
 {name: 'Spear', range: '3/6/12', damage: 'Str+d6', rof: 1, ap: 0, cost: 10, special: 'Users with a Shooting skill of d8 or higher inflict an additional 1d6 damage. Min Str d6.'},
 {name: 'Thermiton Thrower (Vehicular)', range: 'Cone', damage: '3d12', rof: 1, ap: 0, cost: 55, special: 'Heavy Weapon. May not move unless vehicle mounted. May start fires. May be fired as Cone, or MBT up to 18” distant. Affects target’s least armored area.'},
 {name: 'Thermiton Thrower', range: 'Cone', damage: '2d12', rof: 1, ap: 0, cost: 38, special: 'Heavy Weapon, Min Str d8, May start fires. May be fired as Cone, or MBT up to 18” distant. Affects target’s least armored area.'},
 {name: 'Tommy Gun (.45)', range: '12/24/48', damage: '2d6+1', rof: 3, ap: 1, cost: 30},
 {name: 'Torpedo (Light)', range: '150/300/600', damage: '8d12', rof: 1, ap: 40, cost: 244, special: 'Heavy Weapon. Large Blast Template. Watercraft Targets only.'},
 {name: 'Trinamite', range: '4/8/16', damage: '2d8', rof: 1, ap: 0, cost: 3, special: 'One-Shot, Medium Blast Template.'},
 {name: 'Water Pressure Gun', range: '5/10/20', damage: '2d6', rof: 1, ap: 0, cost: 5, special: 'Semi-Auto'},
];
